import {
    AiFillFacebook,
    AiOutlineBarChart,
    AiOutlineExperiment,
    AiOutlineGoogle,
    AiOutlineLoading,
    CgLock,
    CgLockUnlock,
    FcGoogle,
    GiCutDiamond,
    GiMaterialsScience,
    GiSpeedometer,
    HiUsers,
    IoDocumentTextOutline,
    IoHelp,
    IoPersonOutline,
    MdAdd,
    MdCancelPresentation,
    MdCardGiftcard,
    MdCheck,
    MdClose,
    MdContentCopy,
    MdMenu,
    MdOutlineAirplaneTicket,
    MdOutlineCloudDone,
    MdOutlineCloudUpload,
    MdOutlineKeyboardArrowDown,
    MdOutlineKeyboardArrowLeft,
    MdOutlineKeyboardArrowRight,
    MdOutlineKeyboardArrowUp,
    MdOutlineList,
    MdOutlineModeEditOutline,
    MdOutlinePersonPin,
    MdOutlinePhoto,
    MdOutlineShield,
    MdRemove,
    MdTimerOff,
    RiComputerLine,
    RiHome2Fill,
    RiHome2Line,
    RiShareForwardFill,
} from "react-icons/all";

export const icons = {
    home: RiHome2Line,
    homeFilled: RiHome2Fill,
    arrowTop: MdOutlineKeyboardArrowUp,
    arrowRight: MdOutlineKeyboardArrowRight,
    arrowDown: MdOutlineKeyboardArrowDown,
    arrowLeft: MdOutlineKeyboardArrowLeft,
    diamond: GiCutDiamond,
    share: RiShareForwardFill,
    edit: MdOutlineModeEditOutline,
    copy: MdContentCopy,
    check: MdCheck,
    cloud: MdOutlineCloudUpload,
    cloudSuccess: MdOutlineCloudDone,
    help: IoHelp,
    plus: MdAdd,
    minus: MdRemove,
    shield: MdOutlineShield,
    document: IoDocumentTextOutline,
    airplaneTicket: MdOutlineAirplaneTicket,
    time: MdTimerOff,
    giftcard: MdCardGiftcard,
    list: MdOutlineList,
    speed: GiSpeedometer,
    person: IoPersonOutline,
    personPin: MdOutlinePersonPin,
    persons: HiUsers,
    photo: MdOutlinePhoto,
    cross: MdClose,
    temp: MdCancelPresentation,
    hamburger: MdMenu,
    loading: AiOutlineLoading,
    facebook: AiFillFacebook,
    google: AiOutlineGoogle,
    googleColored: FcGoogle,
    lockLocked: CgLock,
    lockUnlocked: CgLockUnlock,
    computer: RiComputerLine,
    math: AiOutlineBarChart,
    chemistry: AiOutlineExperiment,
    physics: GiMaterialsScience,
};
